FORMAT: 1A
HOST: https://bravi-backend.herokuapp.com/

# bravi

Simple Person and Contact API

# People [/people]

## List all people [GET]

+ Response 200 (application/json)

        [
              {
                "id": 1,
                "name": "Mateus",
                "last_name": "Torquato de Medeiros",
                "created_at": "2019-11-07 01:32:23",
                "updated_at": "2019-11-07 01:32:23",
                "contacts": [
                {
                    "id": 1,
                    "name": "Mateus",
                    "last_name": "Torquato contato",
                    "phone": "99999",
                    "whatsapp": "88888",
                    "email": "mat@mat.com",
                    "person_id": 1,
                    "created_at": "2019-11-07 04:30:09",
                    "updated_at": "2019-11-07 04:30:09"
                },
                {
                    "id": 2,
                    "name": "Mateus",
                    "last_name": "Torquato contato",
                    "phone": "99999",
                    "whatsapp": "88888",
                    "email": "mat@mat.com",
                    "person_id": 1,
                    "created_at": "2019-11-07 04:30:46",
                    "updated_at": "2019-11-07 04:30:46"
                }
                ]
              },
              {
                "id": 2,
                "name": "Mateus",
                "last_name": "Torquato de Medeiros",
                "created_at": "2019-11-07 01:32:38",
                "updated_at": "2019-11-07 01:32:38",
                "contacts": []
              },
        ]

## Retrieve person [GET /people/{?id}]

+ Parameters
    + id (integer)

+ Response 200 (application/json)

        {
                "id": 1,
                "name": "Mateus",
                "last_name": "Torquato de Medeiros",
                "created_at": "2019-11-07 01:32:23",
                "updated_at": "2019-11-07 01:32:23",
                "contacts": []
        }

## Insert person [POST /people]

+ Request (application/json)

        {
            "name": "Mateus",
            "last_name": "Torquato"
        }

+ Response 201 (application/json)

    + Body
        
            {
                "valid": true,
                "message": "ok",
                "person": {
                "name": "Mateus",
                "last_name": "Torquato",
                "updated_at": "2019-11-07 03:46:52",
                "created_at": "2019-11-07 03:46:52",
                "id": 28
            }

## Update person [PUT /people/{id}]

+ Parameters
    + id (integer)
    
+ Request (application/json)

        {
            "name": "Mateus",
            "last_name": "Torquato"
        }

+ Response 200 (application/json)

    + Body
                    
            {
              "valid": true,
              "message": "ok",
              "person": {
                "name": "Mateuss",
                "last_name": "Torquato",
                "updated_at": "2019-11-07 03:50:16",
                "created_at": "2019-11-07 03:50:16",
                "id": 29
              }
            }


+ Response 200

## Delete person [DELETE /people/{id}]

+ Parameters
    + id (integer)

+ Response 200

# Contacts [/contacts]

## List all contacts [GET]

+ Response 200 (application/json)

        [
              {
                "id": 1,
                "name": "Mateus",
                "last_name": "Torquato de Medeiros",
                "created_at": "2019-11-07 01:32:23",
                "updated_at": "2019-11-07 01:32:23",
                "contacts": []
              },
              {
                "id": 2,
                "name": "Mateus",
                "last_name": "Torquato de Medeiros",
                "created_at": "2019-11-07 01:32:38",
                "updated_at": "2019-11-07 01:32:38",
                "contacts": []
              },
        ]

## Retrieve contact [GET /contacts/{?id}{?person_id}]

+ Parameters
    + id (integer)
    + person_id (integer)

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Mateus",
            "last_name": "Torquato de Medeiros",
            "created_at": "2019-11-07 01:32:23",
            "updated_at": "2019-11-07 01:32:23",
            "contacts": []
        }

## Insert contact [POST /contacts]

+ Request (application/json)

        {
            "name": "Mateus",
            "last_name": "Torquato contato",
            "phone": "99999",
            "whatsapp": "88888",
            "email": "mat@mat.com",
            "person_id": 1
        }
            
+ Response 201 (application/json)

   + Body

        {
            "valid": true,
            "message": "ok",
            "contact": {
            "name": "Mateus",
            "last_name": "Torquato contato",
            "phone": "99999",
            "whatsapp": "88888",
            "email": "mat@mat.com",
            "person_id": 1,
            "updated_at": "2019-11-07 04:30:46",
            "created_at": "2019-11-07 04:30:46",
            "id": 2
        }


## Update contact [PUT /contacts/{id}]

+ Parameters
    + id (integer)

+ Request (application/json)

        {
            "name": "Mateus",
            "last_name": "Torquato contato",
            "phone": "99999",
            "whatsapp": "88888",
            "email": "mat@mat.com",
            "person_id": 1
        }

+ Response 200 (application/json)

    + Body

            {
                "valid": true,
                "message": "ok",
                "contact": {
                "name": "Mateus",
                "last_name": "Torquato contato",
                "phone": "99999",
                "whatsapp": "88888",
                "email": "mat@mat.com",
                "person_id": 1,
                "updated_at": "2019-11-07 04:30:46",
                "created_at": "2019-11-07 04:30:46",
                "id": 2
            }


+ Response 200

## Delete contact [DELETE /contacts/{id}]

+ Parameters
    + id (integer)

+ Response 204